# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

# Do not use this file for site configuration. Create application.yml
# instead (see application.yml.example).
#
# The order of precedence is:
# 1. config/environments/{RAILS_ENV}.rb (deprecated)
# 2. Section in application.yml corresponding to RAILS_ENV (e.g., development)
# 3. Section in application.yml called "common"
# 4. Section in application.default.yml corresponding to RAILS_ENV
# 5. Section in application.default.yml called "common"

common:

  ## Set Time.zone default to the specified zone and make Active
  ## Record auto-convert to this zone.  Run "rake -D time" for a list
  ## of tasks for finding time zone names. Default is UTC.
  #time_zone: Central Time (US & Canada)

  ## Default encoding used in templates for Ruby 1.9.
  encoding: utf-8

  # Enable the asset pipeline
  assets.enabled: true

  # Version of your assets, change this if you want to expire all your assets
  assets.version: "1.0"

  default_openid_prefix: https://www.google.com/accounts/o8/id

  # Override the automatic version string. With the default value of
  # false, the version string is read from git-commit.version in
  # Rails.root (included in vendor packages) or determined by invoking
  # "git log".
  source_version: false

  # Override the automatic package version string. With the default version of
  # false, the package version is read from package-build.version in Rails.root
  # (included in vendor packages).
  package_version: false

development:
  force_ssl: false
  cache_classes: false
  whiny_nils: true
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_mailer.raise_delivery_errors: false
  action_mailer.perform_deliveries: false
  active_support.deprecation: :log
  action_dispatch.best_standards_support: :builtin
  active_record.auto_explain_threshold_in_seconds: 0.5
  assets.compress: false
  assets.debug: true

production:
  force_ssl: true
  cache_classes: true
  consider_all_requests_local: false
  action_controller.perform_caching: true
  public_file_server:
    enabled: false
  assets.compress: true
  assets.compile: false
  assets.digest: true

test:
  force_ssl: false
  cache_classes: true
  whiny_nils: true
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_dispatch.show_exceptions: false
  action_controller.allow_forgery_protection: false
  action_mailer.delivery_method: :test
  active_support.deprecation: :stderr
  uuid_prefix: zzzzz
  sso_app_id: arvados-server
  sso_app_secret: <%= rand(2**512).to_s(36) %>
  sso_provider_url: http://localhost:3002
  secret_token: <%= rand(2**512).to_s(36) %>
  blob_signing_key: zfhgfenhffzltr9dixws36j1yhksjoll2grmku38mi7yxd66h5j4q9w4jzanezacp8s6q0ro3hxakfye02152hncy6zml2ed0uc
  user_profile_notification_address: arvados@example.com
  workbench_address: https://localhost:3001/
  git_repositories_dir: <%= Rails.root.join 'tmp', 'git', 'test' %>
  git_internal_dir: <%= Rails.root.join 'tmp', 'internal.git' %>
  trash_sweep_interval: -1
  docker_image_formats: ["v1"]
