# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

# Do not use this file for site configuration. Create application.yml
# instead (see application.yml.example).

# Below is a sample setting for diagnostics testing.
# Configure workbench URL as "arvados_workbench_url"
# Configure test user tokens as "user_tokens".
#   At this time the tests need an "active" user token.
# Also, configure the pipelines to be executed as "pipelines_to_test".
# For each of the pipelines identified by the name of your choice
#     ("pipeline_1" and "pipeline_2" in this sample), provide the following:
#   template_uuid: is the uuid of the template to be executed
#   input_paths: an array of inputs for the pipeline. Use either a collection's "uuid"
#     or a file's "uuid/file_name" path in this array. If the pipeline does not require
#     any inputs, this can be omitted.
#   max_wait_seconds: max time in seconds to wait for the pipeline run to complete.
#     Default value of 30 seconds is used when this value is not provided.
diagnostics:
  arvados_workbench_url: https://localhost:3031
  user_tokens:
    active: eu33jurqntstmwo05h1jr3eblmi961e802703y6657s8zb14r
  pipelines_to_test:
    pipeline_1:
      template_uuid: zzzzz-p5p6p-rxj8d71854j9idn
      input_paths: [zzzzz-4zz18-nz98douzhaa3jh2]
      max_wait_seconds: 10
    pipeline_2:
      template_uuid: zzzzz-p5p6p-1xbobfobk94ppbv
      input_paths: [zzzzz-4zz18-nz98douzhaa3jh2, zzzzz-4zz18-gpw9o5wpcti3nib]
  container_requests_to_test:
    container_request_1:
      workflow_uuid: zzzzz-7fd4e-60e96shgwspt4mw
      input_paths: []
      max_wait_seconds: 10

# Below is a sample setting for performance testing.
# Configure workbench URL as "arvados_workbench_url"
# Configure test user token as "user_token".
performance:
  arvados_workbench_url: https://localhost:3031
  user_token: eu33jurqntstmwo05h1jr3eblmi961e802703y6657s8zb14r

development:
  cache_classes: false
  eager_load: true
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_mailer.raise_delivery_errors: false
  active_support.deprecation: :log
  action_dispatch.best_standards_support: :builtin
  assets.debug: true
  profiling_enabled: true

production:
  force_ssl: true
  cache_classes: true
  eager_load: true
  consider_all_requests_local: false
  action_controller.perform_caching: true
  assets.compile: false
  assets.digest: true
  i18n.fallbacks: true
  active_support.deprecation: :notify
  profiling_enabled: false
  log_level: info

test:
  cache_classes: true
  eager_load: false
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_dispatch.show_exceptions: false
  action_controller.allow_forgery_protection: false
  action_mailer.delivery_method: :test
  active_support.deprecation: :stderr
  profiling_enabled: true
  secret_key_base: <%= rand(2**256).to_s(36) %>
  site_name: Workbench:test

  # Enable user profile with one required field
  user_profile_form_fields:
    - key: organization
      type: text
      form_field_title: Institution
      form_field_description: Your organization
      required: true
    - key: role
      type: select
      form_field_title: Your role
      form_field_description: Choose the category that best describes your role in your organization.
      options:
        - Bio-informatician
        - Computational biologist
        - Biologist or geneticist
        - Software developer
        - IT
        - Other

  repository_cache: <%= File.expand_path 'tmp/git', Rails.root %>

common:
  assets.js_compressor: false
  assets.css_compressor: false

  # Override the automatic version string. With the default value of
  # false, the version string is read from git-commit.version in
  # Rails.root (included in vendor packages) or determined by invoking
  # "git log".
  source_version: false

  # Override the automatic package string. With the default value of
  # false, the package string is read from package-build.version in
  # Rails.root (included in vendor packages).
  package_version: false

  # only used by tests
  testing_override_login_url: false
