# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# NOTE that these get overriden by Arvados' own configuration system.

# development:
#   secret_key_base: <%= rand(1<<255).to_s(36) %>

# test:
#   secret_key_base: <%= rand(1<<255).to_s(36) %>

# In case this doesn't get overriden for some reason, assign a random key
# to gracefully degrade by rejecting cookies instead of by opening a
# vulnerability.
production:
  secret_key_base: <%= rand(1<<255).to_s(36) %>
